--DROP TABLE IF EXISTS PRODUIT; 
--DROP TABLE IF EXISTS CATEGORIE;  

--CREATE TABLE PRODUIT (  
--id INT AUTO_INCREMENT  PRIMARY KEY,  
--nom VARCHAR(150) NOT NULL,  
--prix INT(8) NOT NULL,  
--);  

--
--CREATE TABLE CATEGORIE (  
--id INT AUTO_INCREMENT  PRIMARY KEY,  
--nom VARCHAR(150) NOT NULL,
--);  